title: DengYueMed
description: Global Pharma Intelligence Platform
theme: minima

# 分类
collections:
  posts:
    output: true

# 首页显示
show_excerpts: true

url: "https://hkdengyue.github.io"
baseurl: ""

# SEO
author: DengYueMed
lang: en

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
